AWSTemplateFormatVersion: 2010-09-09
Description: >-
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.micro
      - t2.small
    ConstraintDescription: must be a valid EC2 instance type.
# 値のマッピングを行う(上と違い、固定変数を作るみたいな感じ)
# [Name] - [Key] - [List or Map of Attribute] の3階層で宣言する
# Nameに対してKeyという選択肢を作成、Attribute値を埋め込む.使うのはResourcesのProperties
Mappings:
# インスタンスタイプ(AWSInstanceType2Arch)とアーキテクチャ(Arch)のマッピング
  AWSInstanceType2Arch:
    t2.micro:
      Arch: ARM64
    t2.small:
      Arch: X8664
# リージョンとアーキテクチャの組み合わせに対する、AMI ( AWSRegionArch2AMI ) のマッピング
  AWSRegionArch2AMI:
    ap-northeast-1:
      ARM64: ami-0fca7292592ff239f
      X8664: ami-05a03e6058638183d

# --------------リソースを指定--------------
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - !Ref InstanceSecurityGroupFromCompany
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AWSRegionArch2AMI
        - ap-northeast-1
        - !FindInMap
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      Tags:
        - Key: "Name"
          Value: !Ref AWS::StackName

  InstanceSecurityGroupFromCompany:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22

# 出力(コンソール出力なので最悪なくてもなんとかなる)
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt
      - EC2Instance
      - AvailabilityZone
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt
      - EC2Instance
      - PublicIp